### ISSUE TITLE
SSH session multiplexer

### ISSUE THREAD

**Issue by natesales** [fosshostorg/aarch64#14]
Currently we're using [libvirt-sshd](https://github.com/natesales/libvirt-sshd) which only allows a single SSH connection to the VM virtual serial console. It would be neat to implement a session mux so multiple sessions can access a VM console at once. This will also solve the problem of console sessions becoming stuck in connected state if your terminal doesn't exit gracefully.

**Comment by lanefu** [comment]
I feel like borrowing from https://github.com/tmate-io/tmate would somehow get you there.
