### ISSUE TITLE
Support virtio block devices

### ISSUE THREAD

**Issue by lanefu** [fosshostorg/aarch64#22]
You may want this to be a user flag at provisioning for edge cases, but typically using virtio block device on any modern linux is going to be optimal.

https://github.com/natesales/aarch64/blob/4e65af0ad78444f8b7f320feb7d68e633eecd568/provisioning/roles/vms/tasks/main.yml#L64

I'd suggest trying

`--disk path=/opt/aarch64/vms/{{ item["_id"] }}-disk.qcow2,bus=virtio \ `

**Comment by natesales** [comment]
I agree, seems like a sensible default to go with the virtio driver here. Also, maybe we should set an explicit cache setting?

```
cache
    The cache mode to be used. The host pagecache provides cache memory. The cache value can be 'none', 'writethrough', or 'writeback'. 'writethrough' provides read caching. 'writeback' provides read and write caching. 
```
[virt-install(1)](https://linux.die.net/man/1/virt-install)

**Comment by lanefu** [comment]
Given the single disk and shared tenancy id suggest trying writeback.   This will give the VM host a chance to be efficient with write IOs
