### ISSUE TITLE
SSH key management

### ISSUE THREAD

**Issue by natesales** [fosshostorg/aarch64#25]
We should support SSH keys that can be included in the cloud-init config on VM creation time. Most importantly a user should be able to add/delete SSH keys for their account. I think it would also be beneficial to add SSH keys at a project level for things like project-wide provisioning, logging, auditing, etc.

I propose the following implementation:

- API routes to add (validate) and delete SSH keys on both a user and project basis
- A helper function that takes a project ID and returns a list of SSH keys for that project and all associated users
- Call this helper function on VM creation time to add a list of SSH keys to the VM project
- Modify cloud-init template to add to the SSH key list for root
- Add a list in the settings tab of the dashboard to display which keys were used when the VM was created

**Comment by hamptonmoore** [comment]
Would we want the ability to add keys on a per VM basis aswell? or just do it on a per project and per user basis

**Comment by natesales** [comment]
Maybe, although in that case its not hard to just log into the VM with a user's key and add a VM specific one.
