### ISSUE TITLE
Networking Breaks after apt-update and reboot

### ISSUE THREAD

**Issue by lanefu** [fosshostorg/aarch64#28]
Provisioned Ubuntu 20.10 VM.. performed apt-update and reboot.   network interface doesn't come back up.

**Comment by lanefu** [comment]
looks like it's because predictable interfaces names is enabled (ubuntu default), but first boot with clouding is using eth0.

**Comment by natesales** [comment]
We should be able to `ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules` in the cloud-init startup command block for Ubuntu. I'll give this a try later today.

**Comment by lanefu** [comment]
I didn't have much luck with the udev rule to dev null.. its may require me to create new root disk image...

this worked tho

```
sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash net.ifnames=0"/' /etc/default/grub
/usr/sbin/update-grub
```
