### ISSUE TITLE
Add feedback/roadmap link to left nav bar

### ISSUE THREAD

**Issue by MrTBM** [fosshostorg/aarch64#52]
It would be cool to let projects provide feedback and see the roadmap using canny.io
Canny.io have kindly provided us with a free license as a FOSS project
The URL is https://roadmap.aarch64.com/aarch64 and I have already added some suggestions 
I have sent admin invites to canny.io for those who require it so that we can manage this effectively
It would be great to use canny.io as a way of getting feedback through the use of community voting

**Comment by natesales** [comment]
Apologies, I forgot to update this when I added this last week. Added in 19389e9f5e079894aa664f3dd9783c51a17fb67a
