### ISSUE TITLE
Change bird install method

### ISSUE THREAD

**Issue by hamptonmoore** [fosshostorg/aarch64#59]
https://bird.network.cz/pipermail/bird-users/2021-April/015367.html

**Comment by hamptonmoore** [comment]
These are the steps used by forkwhilefork, we could likely base the ansible commands off of it
```echo "deb [arch=amd64] http://provo-mirror.opensuse.org/repositories/home:/CZ-NIC:/bird-latest/Debian_10/  ./" > /etc/apt/sources.list.d/bird2.list
cat << EOF > /etc/apt/preferences.d/bird2
Package: bird*
Pin: origin provo-mirror.opensuse.org
Pin-Priority: 600
EOF
apt install -y gnupg2
apt-key adv --fetch-keys 'https://download.opensuse.org/repositories/home:/CZ-NIC:/bird-latest/Debian_10/Release.key'
apt update
apt install -y bird2```

**Comment by natesales** [comment]
The repo (http://provo-mirror.opensuse.org/repositories/home:/CZ-NIC:/bird-latest/Debian_10/) doesn't have aarch64 packages :/

There may be another repo that I'm not aware of with aarch64 packages, if not we should check in with the new maintainer to see about correcting that.
