### ISSUE TITLE
Users cannot remove themselves from a project

### ISSUE THREAD

**Issue by sario528** [fosshostorg/aarch64#77]
Console users cannot remove themselves from a project once added. As a user can be added to a project without the user's prior knowledge or consent, I think it is important that we have a way for the user to remove themselves from the project.

**Comment by hamptonmoore** [comment]
@GrahamSH-LLK does this interest you? (No is okay)

**Comment by GrahamSH-LLK** [comment]
Yeah, I'll tackle it later.

**Comment by samip5** [comment]
Backend changes done, frontend button is missing for now though.

Code is in https://github.com/fosshostorg/aarch64/tree/remove-self branch.

**Comment by samip5** [comment]
Waits frontend changes.
