### ISSUE TITLE
Make alpine linux an option for self-deployed VMs

### ISSUE THREAD

**Issue by mplscorwin** [fosshostorg/aarch64#81]
This is a frequently requested feature.  Team has already been discussing this; creating an issue for tracking.

Please get code-review from @hamptonmoore and/or @natesales prior to merging.

**Comment by Shinyzenith** [comment]
Thank you so much for making this an option!

**Comment by Shinyzenith** [comment]
Hi, I'd like to maintain the alpine image. If any guidelines can be provided as to your current image generation workflow, that would help immensely.

**Comment by samip5** [comment]
> Hi, I'd like to maintain the alpine image. If any guidelines can be provided as to your current image generation workflow, that would help immensely.

We are using cloud images, aka usually just the normal image with cloud-init enabled.

**Comment by hamptonmoore** [comment]
There are a lot of politics in the alpine world around cloud-init

**Comment by samip5** [comment]
> There are a lot of politics in the alpine world around cloud-init

Yeah, I noticed when searching their gitlab for the generic image request ticket.

For reference: https://gitlab.alpinelinux.org/alpine/cloud/alpine-cloud-images/-/issues/133
